apiVersion: v1
kind: Service
metadata:
  name: backstage-backend-service
spec:
  type: LoadBalancer
  selector:
    app: backstage-backend
  ports:
    - name: http
      port: {{ .Values.backstage.servicePort }}
      targetPort: {{ .Values.backstage.targetPort }}