apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.servicePort }}
  type: ClusterIP