name: Docker Image CI

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:
     
  deploy:
    uses: CSCorpIt/reusable-workflows/.github/workflows/aks_deploy.yml@main
    with:
      azure-aks: 'backstage-aks'
      azure-aks-rg: 'backstage-aks-rg'
    secrets:
      azureClientId: ${{ secrets.AZURE_GITHUB_APP }}
      azureSubId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      
  build:
    needs: deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Log in to the Container registry
       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
       with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
          
     - name: Build the Docker image
       run: |
        yarn install --immutable
        yarn tsc
        yarn build:backend
        docker image build . -f packages/backend/Dockerfile --tag  ${{ env.REGISTRY }}/cscorpit/backstage:latest
        docker push ${{ env.REGISTRY }}/cscorpit/backstage:latest
