name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       yarn install --immutable
       yarn tsc
       yarn build:backend
       docker image build . -f packages/backend/Dockerfile --tag cspower/backstage:latest
       echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
       docker push ghcr.io/dev/backstage:latest
